<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeveloperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeveloperRepository extends EntityRepository
{
	/**
	 * Get random entities
	 *
	 * @param int $count Entities count, default is 12
	 *
	 * @return array
	 */
	public function getRandomEntities($count = 12)
	{
		return $this->createQueryBuilder('d')
					->where('d.isActive = 1')
		            ->addOrderBy('Rand()')
		            ->setMaxResults($count)
		            ->getQuery()
		            ->getResult();
	}
}
